### ISSUE TITLE
Release pinning

### ISSUE THREAD

**Issue by fabaff** [ChristianKuehnel/btlewrap#28]
The release pinning for `bluepy` and `pygatt` is an issue for distribution packages. E.g., Fedora ships pygatt-4.0.5.

**Comment by ChristianKuehnel** [comment]
Similar to miflora: 
I have no clue on how to test compatibility with a range of library versions. This would also require physical hardware. You don't get that on TravisCI.

Beyond that: I do not have the time to set that up and maintain it.
