### ISSUE TITLE
Support for Python 3.9?

### ISSUE THREAD

**Issue by diamant-x** [ChristianKuehnel/btlewrap#47]
Hi,

I'm a user of this library leveraged in this other project https://github.com/mbrentini/homeassistant_parrotflowerpower 

Recently it has stopped working (https://github.com/mbrentini/homeassistant_parrotflowerpower/issues/6), and the root cause seems to be related to the bump to Python 3.9.
https://github.com/home-assistant/core/pull/63883

- Could you check and confirm/fix if your library btlewrap is compatible with Python 3.9 and above?

Thanks!

**Comment by ChristianKuehnel** [comment]
Which backend are you using?

What do you mean by "not working"?
Do you have an error message or stack trace?


diamant-x ***@***.***> schrieb am Fr., 4. März 2022, 17:12:

**Comment by ChristianKuehnel** [comment]
looks like the tests are currently failing on Python 3.9:
https://github.com/ChristianKuehnel/btlewrap/runs/5446828110?check_suite_focus=true

**Comment by ChristianKuehnel** [comment]
I fixed a broken import statement. Please let me know if this solved your issue and I'll create a new releaes...

**Comment by diamant-x** [comment]
Hi,
Many thanks for looking at this. I downloaded the latest source from the master tree and override the current dependency on the related software. Now I no longer get an error related to Bluetooth and my measurements from the Parrot Flower are again captured and displayed. So **this new version is now working fine** (at least under Python 3.9 which is my working case).

Kindly push this to a new release so the related libraries pick it up.
Thanks!

**Comment by ChristianKuehnel** [comment]
Sorry forgot about that.

The problem is that we would need to test this change for the older Python versions and I don't have a setup for testing any more...

**Comment by diamant-x** [comment]
Can't older version support be dropped and push a release only for newest for which you can have a testing setup?
If that's the only setup you have access to then I don't see another solution?

Thanks!

**Comment by ChristianKuehnel** [comment]
I don't have *any* setup for testing at the moment. I just hope this works across versions.

Created a new release: https://pypi.org/project/btlewrap/
